### ISSUE TITLE
Python3 Release

### ISSUE THREAD

**Issue by msom** [klausman/pymetar#1]
Is it possible to release the python 3 branch?

**Comment by klausman** [comment]
I've been meaning to do that. it's a chunk of work around packaging, but I think I can manage to get something together this weekend or the next.

**Comment by msom** [comment]
Let me know if I can help with something!

**Comment by klausman** [comment]
I've just made a release (v1.0, no less!) that is entirely python3 (and pypy3). Have fun :)

**Comment by msom** [comment]
Will you release it also on PyPI (https://pypi.org/project/pymetar)?

**Comment by klausman** [comment]
Yes! See https://pypi.org/manage/project/pymetar/release/1.0/

**Comment by msom** [comment]
Great, thanks a lot!
